id = "rshtml"
name = "RsHtml"
version = "0.1.4"
schema_version = 1
authors = ["rshtml"]
description = "RsHtml Template Language Support"
repository = "https://github.com/rshtml/zed"

[grammars.rshtml]
repository = "https://github.com/rshtml/tree-sitter-rshtml"
rev = "89ae0f3a5e221a83aad243def85e822616d3b3c2"

[language_servers.rshtml-analyzer]
name = "RsHtml"
languages = ["RsHtml"]

[language_servers.rshtml-analyzer.language_ids]
"RsHtml" = "rshtml"

[language_servers.vscode-html-language-server]
name = "vscode-html-language-server"
languages = ["RsHtml", "HTML"]

[language_servers.vscode-html-language-server.language_ids]
"HTML" = "html"
"CSS" = "css"
"RsHtml" = "rshtml"
